[phases.setup]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[phases.install]
cmds = ["python manage.py migrate"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"