[build]
builder = "nixpacks"

[build.environment]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "./start.sh"

[[services]]
port = 8000

[environments.production.variables]
DEBUG = "False"